"""LaTeX report generation."""
import os
from ..utils.config import OUTPUT_DIR, logger

def generate_report(results, stages, output_dir=OUTPUT_DIR):
    """Generate a LaTeX report with optimization results."""
    try:
        if not results:
            logger.error("No results to include in report")
            return None
            
        report_path = os.path.join(output_dir, "report.tex")
        
        # Extract global parameters
        g0 = float(stages[0].get('G0', 9.81))  # Standard gravity
        
        # Create stage parameters table data
        stage_data = [(stage['stage'], stage['ISP'], stage['EPSILON']) for stage in stages]
        
        report_content = r"""\documentclass{article}
\usepackage{booktabs}
\usepackage{caption}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\usepackage{float}
\usepackage{array}
\usepackage{siunitx}
\sisetup{scientific-notation=true}

\begin{document}
\title{Rocket Stage Optimization Report}
\author{Generated by Payload Optimization Script}
\maketitle

\section{Problem Definition}
\subsection{Input Parameters}
\begin{table}[H]
\centering
\caption{Global Parameters}
\begin{tabular}{lc}
\toprule
Parameter & Value \\
\midrule
G0 & """ + f"{g0:.2f}" + r""" \\
\bottomrule
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{Stage Parameters}
\begin{tabular}{ccc}
\toprule
Stage & ISP & EPSILON \\
\midrule"""

        # Add stage data
        for stage, isp, epsilon in stage_data:
            report_content += f"\n{stage} & {isp:.3f} & {epsilon:.3f} \\\\"
        
        report_content += r"""
\bottomrule
\end{tabular}
\end{table}

\section{Performance Analysis}
\subsection{Execution Time}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{execution_time.png}
\caption{Execution time comparison between solvers}
\end{figure}

\subsection{Payload Fraction}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{payload_fraction.png}
\caption{Payload fraction comparison between solvers}
\end{figure}

\subsection{Delta-V Breakdown}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{dv_breakdown.png}
\caption{Delta-V breakdown by solver}
\end{figure}

\section{Optimization Results}
\begin{table}[H]
\centering
\caption{Optimization Results by Solver}
\small
\begin{tabular}{lcccc}
\toprule
Method & Time (s) & Payload Fraction & $\Delta$V & Mass Ratio \\
\midrule"""

        # Add results data
        for method, data in results.items():
            time = data.get('time', 0)
            payload = data.get('payload_fraction', 0)
            dv = data.get('optimal_dv', [0, 0])
            ratios = data.get('stage_ratios', [0, 0])
            
            dv_str = f"{dv[0]:.2f}, {dv[1]:.2f}"
            ratio_str = f"{ratios[0]:.2f}, {ratios[1]:.2f}"
            
            report_content += f"\n{method} & {time:.6f} & {payload:.6f} & {dv_str} & {ratio_str} \\\\"

        report_content += r"""
\bottomrule
\end{tabular}
\end{table}

\end{document}
"""

        with open(report_path, 'w') as f:
            f.write(report_content)
        
        logger.info(f"Generated LaTeX report at {report_path}")
        return report_path
        
    except Exception as e:
        logger.error(f"Error generating LaTeX report: {e}")
        return None
